spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.10:3306/sell?characterEncoding=utf-8&useSSL=false
#  配置全局忽略 json 的 null 字段返回
  jackson:
    default-property-inclusion: non_null


server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx2185fd6d08c322c7
  mpSecret: 21a0df22eff4c4101830e9a6a06dfbd7
  mchId:
  mchKey:
  keyPath:
  notifyUrl: http://vkzjxb.natappfree.cc/sell/pay/notify
